### ISSUE TITLE
@modl directive will generate correspondent dynamodb table

### ISSUE THREAD

**Issue by brucevilo1013** [onlybakam/datastore-mysql-posts#1]
Hi @onlybakam  Thanks for good post in AWS blog.

However, when I run amplify push, It generates correspondent dynamodb tables.
Could you please let me know how to prevent this?
Thanks in advance.

**Comment by brucevilo1013** [comment]
And It will support RDS MSSQL?

**Comment by brucevilo1013** [comment]
Thanks again for good article.

**Comment by onlybakam** [comment]
Hey, I'd recommend taking a look at the latest version of Amplify Gen2 which has direct support for relational databases.

https://docs.amplify.aws/react/build-a-backend/data/connect-to-existing-data-sources/connect-postgres-mysql-database/

**Comment by brucevilo1013** [comment]
Hi @onlybakam Thanks for your recommendation.
But as you know, the amplify gen 2 does not support datastore.
I need to use datastore for offline mode.
Thanks.
